version: '2'
services:
    mysql:
        image: daocloud.io/ld00000/azkaban-mysql:1.0.0
        restart: always
        environment:
            - MYSQL_USER=azkaban
            - MYSQL_PASSWORD=passw0rd
            - MYSQL_DATABASE=azkaban
            - MYSQL_ROOT_PASSWORD=passw0rd
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
           - 3306:3306

    azkaban-exec-server:
        image: daocloud.io/ld00000/azkaban-exec-server
        restart: always
        depends_on:
            - mysql
            - hadoop
        environment:
            - HADOOP_HOME=hadoop
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
#       ports:
#           - "12321:12321"

    azkaban-web-server:
        image: daocloud.io/ld00000/azkaban-web-server
        restart: always
        depends_on:
            - azkaban-exec-server
            - mysql
        ports:
            - "8082:8081"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

    influxdb:
        image: influxdb
        environment:
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUX_USERNAME=influx
            - INFLUX_PASSWORD=influx
        ports:
            - 8083:8083
            - 8086:8086
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

    grafana:
        image: grafana/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=grafana
        depends_on:
            - influxdb
        ports:
            - 3000:3000
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro

    hadoop:
        image: sequenceiq/hadoop-docker:2.7.1
        restart: always

